In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-1.72316361  0.29788656  0.11623194  1.29920695  2.14794291]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-1.72316361  0.29788656  0.11623194  1.29920695  2.14794291]


In [5]:
print(np.dot(a, a.T))

9.37313655553


In [6]:
b = np.random.randn(5, 1)
print(b)

[[ 0.4667419 ]
 [ 1.73952577]
 [ 0.38648333]
 [-0.59214528]
 [-2.74403407]]


In [7]:
print(b.T)

[[ 0.4667419   1.73952577  0.38648333 -0.59214528 -2.74403407]]


In [8]:
print(np.dot(b, b.T))

[[ 0.217848    0.81190956  0.18038796 -0.27637901 -1.28075567]
 [ 0.81190956  3.0259499   0.67229772 -1.03005197 -4.77331797]
 [ 0.18038796  0.67229772  0.14936937 -0.22885428 -1.06052343]
 [-0.27637901 -1.03005197 -0.22885428  0.35063603  1.62486682]
 [-1.28075567 -4.77331797 -1.06052343  1.62486682  7.52972295]]
